INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ADAPTIVEFILTER AdaptiveFilter)

FIND_PATH(
    ADAPTIVEFILTER_INCLUDE_DIRS
    NAMES AdaptiveFilter/api.h
    HINTS $ENV{ADAPTIVEFILTER_DIR}/include
        ${PC_ADAPTIVEFILTER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ADAPTIVEFILTER_LIBRARIES
    NAMES gnuradio-AdaptiveFilter
    HINTS $ENV{ADAPTIVEFILTER_DIR}/lib
        ${PC_ADAPTIVEFILTER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ADAPTIVEFILTER DEFAULT_MSG ADAPTIVEFILTER_LIBRARIES ADAPTIVEFILTER_INCLUDE_DIRS)
MARK_AS_ADVANCED(ADAPTIVEFILTER_LIBRARIES ADAPTIVEFILTER_INCLUDE_DIRS)

